version: '3.4'

services:
  library-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "securePassw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  carservice-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: carservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d carservice"]
      interval: 10s
      retries: 5

  library:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: ./LibraryWebService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      library-db:
        condition: service_healthy
    restart: on-failure

  carserviceapi:
    image: ${DOCKER_REGISTRY-}carserviceapi
    build:
      context: ./CarService-WebService
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      carservice-db:
        condition: service_healthy
    restart: on-failure