version: '3.4'

services:
  webservice-db:
    image: postgres:latest
    environment:
        POSTGRES_DB: carservice-db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    restart: on-failure
    ports:
      - "5432:5432"

  carserviceapi:
    image: ${DOCKER_REGISTRY-}carserviceapi
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - webservice-db
    restart: on-failure